### PR TITLE
including (new) astroplan v0.1!

### PR DESCRIPTION
**Pull request by bmorris3**

### CODE REVIEW

**Comment by cdeil** [comment]
@mwcraig – I see this in every build log:

```
error: [Errno 2] No such file or directory: '/Users/travis/conda/envs/_build/info/index.json'
```

https://travis-ci.org/astropy/conda-builder-affiliated/jobs/78846795#L490

Is this normal or an issue?
Otherwise this looks OK?

**Comment by mwcraig** [comment]
@cdeil -- odd, that is a new one. Checking on it...

**Comment by mwcraig** [comment]
Looks like a regression in `conda-build`. Reporting....will code up a workaround in the morning.

**Comment by mwcraig** [comment]
@bmorris3 -- turns out there a number of things that had to be fixed to get this and it dependencies working. Could you please either rebase, or close this PR and open a new one?

**Comment by bmorris3** [comment]
Sure @mwcraig, I'll close and reopen.

**Pull request closed without merging**
