### PR TITLE
Add omnifit 0.2.1

### LINKED ISSUE #61: Add new affiliated omnifit to requirements

### PR DESCRIPTION
**Pull request by mwcraig**
Closes #61

### CODE REVIEW

**Comment by mwcraig** [comment]
Holding off on this until 0.2.1 is released. Turns out the version number for 0.2 is 0.2 on pypi, but the file name is 0.2.0...and I don't feel like special casing it (though I'll open up an issue for the real fix, which would be determining the download URL and templating that in instead of constructing it based on the version number).

**Comment by mwcraig** [comment]
@RiceMunk -- fyi, omnifit is now available on the conda channel for astropy affiliated packages, so this should work: `conda install -c astropy omnifit`. The channel also includes any dependencies that are not already provided by continuum.

**Comment by RiceMunk** [comment]
@mwcraig Nice! I'll make sure to try and keep an eye on the conda installation working as it should, whenever I update omnifit. :)

**Comment by mwcraig** [comment]
@RiceMunk - thanks! All you should need to do here is update the version number in requirements.yml when you do a new release.

**Pull request merged**
