### PR TITLE
update naima to v0.6

### PR DESCRIPTION
**Pull request by zblz**

### CODE REVIEW

**Comment by zblz** [comment]
It seems its having the same problem as seen in astroplan in #51: astropy helpers trying to upgrade. Should I add a recipe template or can this be solved in another way?

**Comment by mwcraig** [comment]
I'd like to fix the broader issue if I can. The funny thing is that I can't reproduce the issue locally.

**Comment by zblz** [comment]
I agree, it would be best to have it work without recipes. In the meantime, can I build the conda packages and send them to you to upload to binstar?

**Comment by mwcraig** [comment]
Sure, or I can build them locally. I'm going to end up doing that for astroplan in the short run, too, I think.

**Comment by mwcraig** [comment]
Ended up doing this in #54 in the interest of speed -- naima should be uploaded within an hour or so.

**Comment by zblz** [comment]
Thanks!

**Pull request closed without merging**
