### PR TITLE
Add galpy 1.1

### PR DESCRIPTION
**Pull request by mwcraig**
I know the build will fail. Need to decide how to handle
- [ ] GSL dependency (causes the fail currently)
- [ ] OpenMP (can be turned on on linux and windows easily, mac takes a little more effort, i.e. not clang).
- [x] Add recipe to eliminate test that fails https://travis-ci.org/astropy/conda-builder-affiliated/jobs/99649561#L1423

### CODE REVIEW

**Comment by mwcraig** [comment]
@jobovy -- I maintain the conda builds for astropy affiliated packages and am just getting around to adding galpy. A few questions:
- Is there an option like `--no-openmp` to turn off GSL support? Assuming the answer is no, then...
- ...I'll need to put together a conda recipe for GSL, which may take a little while. Neither bad nor good, just a heads up. A little while may well end up meaning months...
- Is there any compelling reason to support Windows? I'm guessing that it would require some extensive modification of the GSL source to compile with the MS compiler (which is what needs to be used on Windows to match the compiler used to build python).

**Comment by jobovy** [comment]
Hi Matt,

If the GSL is installed, the galpy installation will fall back to a Python-only version. However, the functionality of the code is then limited (almost everything works, but it is much slower). I'm surprised that there isn't a conda recipe for the GSL, as it is such a commonly used library (is it this: https://github.com/conda/conda-recipes/tree/master/gsl?). So if it's too difficult, it's okay to build without the GSL, but it would be preferable to build with the GSL.

I don't think Windows needs to be supported; I haven't heard from anybody about using galpy on Windows.

Thanks,

Jo

**Comment by mwcraig** [comment]
Thanks for the recipe -- looks like it will be easiest (on mac at least) to wait until gcc 4.9.4 is released to [fix this issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66509) with the newest xcode tools, though a  [patch is possible](http://trac.sagemath.org/ticket/19234).

Actually, travis runs an older xcode than I have, so maybe gsl could be compiled without too much pain. Will need to do a little hack of the affiliate builder first to handle non-python packages.

In the meantime, I'll get this to pass without gsl (but will hold off on merging until gsl works).

**Comment by mwcraig** [comment]
Closing, since galpy is now on conda-forge.

**Pull request closed without merging**
