### PR TITLE
Update wcsaxes to 0.6

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by astrofrog** [comment]
And yes, before you asked, I missed out a version (0.5) accidentally ;)

**Comment by mwcraig** [comment]
Looks good, merging! Should be uploaded on all platforms soon. (right now the CI status isn't actually accurate, but will be soon)

**Comment by astrofrog** [comment]
I noticed that it was already online before you merged the PR - should we add a clause to `.travis.yml` to make the upload only happen when on master?

**Comment by mwcraig** [comment]
I think that happened because you made a branch on this repo instead of on a fork, so the binstar token was available to the build (it isn't for pull requests from forks).

I don't think it will usually be a problem, but feel free to open an issue.

**Comment by astrofrog** [comment]
Oops that was unintentional.

**Pull request merged**
