### PR TITLE
Update iminuit to 1.2 and remove restriction to python 2 only

### PR DESCRIPTION
**Pull request by mwcraig**
The only reason there was a recipe was that iminuit 1.1.1 could only run
on python 2, so deleted the recipe.

### CODE REVIEW

**Comment by mwcraig** [comment]
@cdeil -- the appveyor fail is not one you can fix in iminuit itself. It is a consequence partially of the design of the builder and current...deficiencies...in conda-build itself. 

A couple of questions about iminuit, both of which I think I know the answers to but would like confirmation:
- It has compiled extensions, correct? 
-  Those extensions do _not_ link to or depend on numpy?

**Comment by cdeil** [comment]
> It has compiled extensions, correct?

Yes. There's a bundled C++ package: MINUIT.
And iminuit is mostly written in Cython

> Those extensions do not link to or depend on numpy?

I'm not 100% sure.
There is one utility methods in the Cython code where numpy is imported:
https://github.com/iminuit/iminuit/blob/master/iminuit/_libiminuit.pyx#L575
The import is in the method, so numpy is an optional dependency that's only needed if that method is called.
Does this count as  "links to or depends on numpy"?

**Comment by mwcraig** [comment]
> Does this count as "links to or depends on numpy"?

Good question...the issue is whether iminuit needs to be built separately for each version of numpy, which in turn depends on whether that particular part of the numpy ABI changed from earlier versions (the ABI tries hard to be backwards compatible, but is not forwards compatible).

It is easy enough to try an experiment. Can you install iminuit 1.2, built in an environment with numpy 1.10, into an environment with numpy 1.9 and try invoking that method to see what happens? It is in my anaconda channel at the moment, so this should do it:

```
conda create -n iminuit-test -c mwcraig iminuit=1.2 numpy=1.9
```

**Comment by mwcraig** [comment]
@cdeil -- this ended up being fixed in another pr, should be available shortly on the astropy channel (builds are happening now).

**Comment by cdeil** [comment]
Thanks!

**Pull request closed without merging**
