### PR TITLE
sncosmo v1.1.0

### PR DESCRIPTION
**Pull request by kbarbary**
This. Is. Sweet.

### CODE REVIEW

**Comment by mwcraig** [comment]
@kbarbary -- thanks! Could you try deleting the recipe template for sncosmo? I think the only reason it needed a recipe was the `six` import issue I did a PR for a while ago.

Thanks!

**Comment by kbarbary** [comment]
Done, tests running...

**Comment by mwcraig** [comment]
Rebuilding the appveyor tests...there was a fail unrelated to sncosmo.

**Comment by mwcraig** [comment]
I'm going to merge...there is actually an appveyor problem when it tries testing sncosm (a Windows permissions error, not a sncosmo error) but I don't _think_ it will prevent the building of the package.

**Comment by kbarbary** [comment]
Hmmm... I recently enabled appveyor tests on the sncosmo repo itself and they seem to pass: https://ci.appveyor.com/project/kbarbary/sncosmo/branch/master

**Comment by mwcraig** [comment]
Right, the fail is completely a Windows fail before it even tries to test anything. The only "testing" conda does is trying to import the packages it builds.

Just as `bdist_conda` starts its tests:

```
TEST START: sncosmo-1.1.0-np19py27_0
error: [Error 5] Access is denied: 'C:\\conda\\envs\\_build\\Lib\\site-packages\\numpy\\core\\libiomp5md.dll'
```

which is a permissions error that pops up more or less randomly sometimes.

**Comment by mwcraig** [comment]
Looks like the packages are being upload to anaconda.org, so all is well.

**Comment by kbarbary** [comment]
Excellent, thanks.

**Comment by mwcraig** [comment]
No problem, this PR reduced the number of lines of code that need to be maintained by almost 100!

**Pull request merged**
