### PR TITLE
Add healpy

### PR DESCRIPTION
**Pull request by cdeil**
This PR is a first attempt to add healpy.
See #48

### CODE REVIEW

**Comment by mwcraig** [comment]
@cdeil -- looks like we just need to limit the numpy versions this tries to build for. WIll come back to this later today.

**Comment by mwcraig** [comment]
@cdeil -- could you please try adding astropy to `requirements.yml`?

**Comment by cdeil** [comment]
@mwcraig - I've made a new pull request adding astropy to requirements.yml: #94 
Is this OK? Or should I add it in this PR?

**Comment by mwcraig** [comment]
@cdeil -- that works.

**Comment by mwcraig** [comment]
@cdeil -- sorry for the delay. What numpy versions do you need this built for?

**Comment by cdeil** [comment]
> What numpy versions do you need this built for?

Is it really necessary to have different healpy packages for different Numpy versions?
Or can one binary work for different Numpy versions?

As I think you know, we had big issues with Sherpa in the past months, because they pinned Numpy to an older version than Astropy in their conda package.
Now they changed to no longer pin the Numpy version and it works just fine with all the Numpy versions from different years.

If you have to pin --- maybe use whatever Astropy is using or the range of versions commonly in use these days?

**Comment by mwcraig** [comment]
I think the difference with sherpa is that they are coupled to numpy in only a couple of places...healpy relies more directly on the numpy C API (or at least  does `cimport numpy` in their cython, which as I understand it means they are using the C API somewhere in the cython).

That isn't to say it might not work to no longer pin numpy.

I'll implement a way to limit numpy versions and get this built.

**Comment by cdeil** [comment]
@mwcraig - Thanks!

I see that the jobs on travis-ci failed because of a package version conflict:
https://travis-ci.org/astropy/conda-builder-affiliated/jobs/107461492#L817

@mwcraig - Is there something I should do here or are you taking over?

**Comment by mwcraig** [comment]
I'll take over --- I've actually moved most off the build to a different repo, where I'll fix the numpy issue.

**Comment by cdeil** [comment]
@mwcraig added a healpy conda package here: https://github.com/OpenAstronomy/conda-channel/pull/3

Closing this now.

**Pull request closed without merging**
