### PR TITLE
sncosmo v1.2.0

### PR DESCRIPTION
**Pull request by kbarbary**

### CODE REVIEW

**Comment by mwcraig** [comment]
@kbarbary -- after some tinkering locally I've worked out that the problem is that `ah_bootstrap` doesn't play nicely with `bdist_conda` (unless you run it twice). While this may be related to astropy-helpers#89, I think the proper fix here is to make a recipe for sncosmo and list `astropy-helpers` as a build dependency.

May take me a few days to get around to that...

**Comment by kbarbary** [comment]
Bumped to new release version 1.2.0. Let me know if there's something you'd like me to look into here.

**Comment by mwcraig** [comment]
@kbarbary -- hoping to have this building correctly later today....

**Comment by mwcraig** [comment]
@kbarbary -- made some extensive changes to the affiliate builder, have opened a different PR #74 to update sncosmo.

**Pull request closed without merging**
