### PR TITLE
Add python-cpl version 0.7

### LINKED ISSUE #63: Add new affiliated package python-cpl

### PR DESCRIPTION
**Pull request by mwcraig**
edit: Closes #63

### CODE REVIEW

**Comment by mwcraig** [comment]
@olebole -- I've got python-cpl building on mac and linux fine. I can _probably_ get it building on windows...but before going down that road I wanted to see whether you thought it was important. If, for example, CPL doesn't work on Windows then there isn't much reason to get python-cpl working. 

Please let me know either way...

**Comment by olebole** [comment]
I know that CPL (and python-cpl) is used on MacOS and Linux; I never heard of a use on Windows. So, it can be probably left out.
However, I will ask on the cpl-help mailing list whether they have any known Windows installations.

**Comment by mwcraig** [comment]
OK, for now I'll just exclude Windows from the builds. python-cpl should be available from the astropy conda channel by the end of the day.

**Comment by olebole** [comment]
Nice! Thank you very much for your efforts!

**Comment by olebole** [comment]
I just got the confirmation that the CPL developers did not get any request to have CPL under Windows. Therefore we are on the safe side by ignoring this OS here :-)

**Comment by mwcraig** [comment]
Excellent, thanks!

**Pull request merged**
