### PR TITLE
add naima to requirements.txt

### PR DESCRIPTION
**Pull request by zblz**
From discussion in #33

### CODE REVIEW

**Comment by mwcraig** [comment]
@zblz -- right now `conda-affiliate-builder` has this really bad "feature" that builds that fail still report as successes on the CI services (note to self: fix #8  one of these days).

Looks like `emcee` is required for `naima`. Could you please add `emcee` to `requirements.txt` _before_ `naima`? Packages are built in the order listed in `requirements.txt` if the here isn't a recipe for the package.

Thanks!

**Comment by zblz** [comment]
Ok, now it looks like it's really building the packages. Will all built packages (i.e., including emcee) be available in the conda channel?

**Comment by mwcraig** [comment]
@zblz -- they will be available once the merge build runs, maybe 15-20 minutes unless travis is backed up.

Thanks for contributing this!

**Comment by cdeil** [comment]
@zblz , @mwcraig – Thanks!

I'll slightly update the Gammapy install bash script to conda install naima instead of pip-installing it now.

**Pull request merged**
