### PR TITLE
Update Gammapy to 0.3

### PR DESCRIPTION
**Pull request by cdeil**
This PR updates Gammapy to version 0.3 (https://pypi.python.org/pypi/gammapy/0.3).

I still need to update the list of command line tools and modules here:
https://github.com/astropy/conda-builder-affiliated/blob/master/recipe_templates/gammapy/meta.yaml

@mwcraig – Is this the right thing to do? Update `meta.yaml` with each release?
I think that's OK, because older versions never need to be re-built?

### CODE REVIEW

**Comment by mwcraig** [comment]
IIRC the only reason `gammapy` needed a recipe was that one of the scripts had a typo in the import. What I would do is completely delete the `gammapy` recipe template and let's see if it builds.

**Comment by cdeil** [comment]
@mwcraig – You mean remove the whole folder like I did in  bb82453 ?

(I'm  offline now until tomorrow :sleeping:)

**Comment by mwcraig** [comment]
@cdeil - yes, that was correct. Builds succeeded so I'll merge. By the time you are back 0.3 will be available and this repo will be 180 lines lighter, so two wins!

**Comment by cdeil** [comment]
@mwcraig – Thanks a lot!

I have two more questions. :smile: 
1. By removing the `test` section in `meta.yml` for Gammapy, did we loose some testing of the imports and commands?
2. Is there a simple way with conda to declare "recommended" or "all" optional dependencies?

I.e. instead of the command from [here](https://gammapy.readthedocs.org/en/latest/install.html#id1):

```
conda install gammapy naima \
    scipy matplotlib ipython-notebook
```

I think it would be nice if one could say

```
conda install gammapy[recommended]
```

**Comment by mwcraig** [comment]
@cdeil 
1. No, the test still occurs[1], but it is auto-generated by `bdist_conda`.
2. Not that I know of...one way to handle might be to revive the recipe and list _all_ of the optional stuff as required since there is no risk accidentally starting a compiler. That would be a good question to ask either on the [anaconda google group](https://groups.google.com/a/continuum.io/forum/#!forum/anaconda) or the [conda google group](https://groups.google.com/a/continuum.io/forum/#!forum/conda). The question would be in-scope for either, but there tends to be less noise on the conda list.

[1] Those tests are not actually running on appveyor because the build chokes as it is entering the test phase because of a file permission issue on windows. They do run on linux and mac, though, and the only time they've succeeded on linux/mac but not on windows was when the script wasn't declared as an entry point.

**Pull request merged**
