### PR TITLE
Add astroscrappy to requirements and a recipe template for it

### LINKED ISSUE #64: Add new affiliated package astro-scrappy
PyPI name: astroscrappy

### PR DESCRIPTION
**Pull request by mwcraig**
Closes #64

### CODE REVIEW

**Comment by mwcraig** [comment]
@cmccully -- with a couple of minor modifications (PR later today on astroscrappy to fix those) this now builds on all platforms.

I'm not compiling with OpenMP support though...how important is that?

**Comment by cmccully** [comment]
It would be preferred. The CR rejection is almost embarrassingly parallel so without openMP you lose a lot of performance. This is some logic in the setup.py that checks for openMP and uses it if the compiler supports it. Is that useable here?

**Comment by mwcraig** [comment]
Probably; I'll dig a bit later today into using openMP on mac (looks like clang doesn't allow it but gcc does) and Windows. I know it should be straightforward to make it work on linux.

**Comment by cmccully** [comment]
That is correct. Clang is in the process of adding openmp support though.

**Comment by mwcraig** [comment]
May be a silly question, but: OpenMP is not the same as openmpi, correct?

Maybe a better question is whether openmp is a separate library or amounts to choosing the right compiler flags for each platform?

**Comment by mwcraig** [comment]
Turns out your setup.py check is working properly, so  linux builds are compiled with openmp support but mac currently are not.

Somewhat to my surprise, microsoft's compiler claims openmp support, will look into that tomorrow...

**Comment by mwcraig** [comment]
@cmccully -- I'm going to go ahead and merge this. Your current check already enabled OpenMP on linux. I was able to get it working on windows (except python 3.4 -- related to the MS compiler used to build that version of python, not to python itself). Sadly, the only platform without OpenMP remains mac. It's clang doesn't support OpenMP AFAIK.

**Pull request merged**
