### PR TITLE
Updated WCSAxes to 0.4

### PR DESCRIPTION
**Pull request by astrofrog**
@mwcraig - is this all that's needed to update a package?

### CODE REVIEW

**Comment by mwcraig** [comment]
@astrofrog -- in principle, yes. The fail here is because `matplotlib` isn't listed as a build requirement. Now that `bdist_conda` was updated to lowercase package names you should be able to delete the recipe template entirely. Can you please do that and we'll see if it builds?

**Comment by astrofrog** [comment]
Done - let's see if that works!

**Comment by mwcraig** [comment]
Looks like it worked. The upload won't happen until it is merged, though.

**Comment by astrofrog** [comment]
Thanks!

**Pull request merged**
