### PR TITLE
Adding (new) astropy-affiliated package `astroplan` v0.1

### PR DESCRIPTION
**Pull request by bmorris3**
Reopening after difficulties in #43. cc @mwcraig

### CODE REVIEW

**Comment by mwcraig** [comment]
That is odd, not used to something building on windows only!

Could you please also add `pytz` to the requirements list, anywhere  before `astroplan`? We'll see what happens with the builds after that. Weird thing is I can build locally without a problem.

**Comment by bmorris3** [comment]
Let's see how that works @mwcraig .

**Comment by mwcraig** [comment]
Apparently the cold I'm getting is worse than I thought...`pytz` is already built by continuum, so we don't need it after all, so please remove that (one bonus: it exposed a problem in the current code with `tar.bz2` archives).

I'm still trying to track down the original problems on linux/mac, not likely to get it solved before some time Tuesday...

**Comment by bmorris3** [comment]
@mwcraig I won't be able to keep up with this for the rest of the week, I'll be traveling without internet. I'm cc'ing @cdeil and @eteq in the hopes that one of them can stay on top of this in my absence. Thanks!

**Comment by cdeil** [comment]
Since @bmorris3 is away for the week, I've opened a new PR #51 to add `astroplan`, where I don't add `pytz` because it's already in the main anaconda channel, as @mwcraig said.

**Pull request closed without merging**
